version: '2.2'
services:
  rabbit1:
    image: rabbitmq:3-management
    mem_limit: 500m
    mem_reservation: 100m
    memswap_limit: 500m
    environment:
     - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
     - RABBITMQ_DEFAULT_USER=rabbitmq
     - RABBITMQ_DEFAULT_PASS=rabbitmq
     - RABBITMQ_DEFAULT_VHOST=/
    ports:
     - "15672:15672"
     - "5672:5672"
